{"uuid": "731509f6-445a-4b49-a4a9-45e11ec8a0bd", "children": ["1844da78-bc9a-4d05-a8d7-5b58a002f7c7"], "befores": [{"name": "log_in", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button class=\"button_button__33qZ0 button_button_type_primary__1O7Bx button_button_size_large__G21Vg\"> is not clickable at point (1148,440) because another element <div class=\"Modal_modal_overlay__x2ZCr\"> obscures it\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:192:5\nElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:336:5\nwebdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:176:11\ninteraction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:135:11\nclickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:204:29\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:84:31\n\n", "trace": "  File \"/home/ubuntupc/yandex/Sprint_6/.venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntupc/yandex/Sprint_6/.venv/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/home/ubuntupc/yandex/Sprint_6/.venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ubuntupc/yandex/Sprint_6/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/ubuntupc/yandex/Sprint_6/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 884, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/ubuntupc/yandex/Diplom/Diplom_3/conftest.py\", line 55, in log_in\n    base_page.click_to_element(enter_to_account)\n  File \"/home/ubuntupc/yandex/Sprint_6/.venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/ubuntupc/yandex/Diplom/Diplom_3/pages/base_page.py\", line 25, in click_to_element\n    self.driver.find_element(*locator).click()\n  File \"/home/ubuntupc/yandex/Sprint_6/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py\", line 94, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"/home/ubuntupc/yandex/Sprint_6/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py\", line 395, in _execute\n    return self._parent.execute(command, params)\n  File \"/home/ubuntupc/yandex/Sprint_6/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/home/ubuntupc/yandex/Sprint_6/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Принимаем экземпляр драйвера и сохраняем его в атрибут self.driver", "status": "passed", "parameters": [{"name": "driver", "value": "<selenium.webdriver.firefox.webdriver.WebDriver (session=\"1f4828d0-e75b-4c0b-ba16-4da054c09154\")>"}], "start": 1716061794586, "stop": 1716061794587}, {"name": "Создаем метод, который содержит в себе условное ожидание, пока элемент не станет кликабильными выполяем клик, по элементу, с использованием метода класса WebDriver- find_element", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button class=\"button_button__33qZ0 button_button_type_primary__1O7Bx button_button_size_large__G21Vg\"> is not clickable at point (1148,440) because another element <div class=\"Modal_modal_overlay__x2ZCr\"> obscures it\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:192:5\nElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:336:5\nwebdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:176:11\ninteraction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:135:11\nclickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:204:29\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:84:31\n\n", "trace": "  File \"/home/ubuntupc/yandex/Sprint_6/.venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/ubuntupc/yandex/Diplom/Diplom_3/pages/base_page.py\", line 25, in click_to_element\n    self.driver.find_element(*locator).click()\n  File \"/home/ubuntupc/yandex/Sprint_6/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py\", line 94, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"/home/ubuntupc/yandex/Sprint_6/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py\", line 395, in _execute\n    return self._parent.execute(command, params)\n  File \"/home/ubuntupc/yandex/Sprint_6/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/home/ubuntupc/yandex/Sprint_6/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "parameters": [{"name": "locator", "value": "('xpath', \".//div/button[@class = 'button_button__33qZ0 button_button_type_primary__1O7Bx button_button_size_large__G21Vg' and text()= 'Войти в аккаунт']\")"}], "start": 1716061794587, "stop": 1716061794626}], "start": 1716061794586, "stop": 1716061794626}], "start": 1716061794586, "stop": 1716061794647}